import { AgentLogEntry, AgentStatus, Incident } from '@/types/agent';

/**
 * Abstract base class for all CogniSIFT agents.
 * Defines the core structure and common functionalities for agents.
 */
export abstract class BaseAgent {
  public readonly id: string;
  public readonly name: string;
  protected currentStatus: AgentStatus['status'];
  protected logs: AgentLogEntry[] = [];

  constructor(id: string, name: string) {
    this.id = id;
    this.name = name;
    this.currentStatus = 'idle';
  }

  /**
   * Initializes the agent, performs any setup needed.
   * @param config - Configuration object specific to the agent.
   */
  public abstract init(config?: Record<string, any>): Promise<void>;

  /**
   * Executes the agent's primary logic for a given incident context.
   * @param incident - The current incident context.
   * @param inputs - Specific inputs required for this execution cycle.
   * @returns A promise resolving to the agent's output.
   */
  public abstract execute(incident: Incident, inputs: any): Promise<any>;

  /**
   * Retrieves the current status of the agent.
   * @returns The agent's current status.
   */
  public getStatus(): AgentStatus {
    return {
      id: this.id,
      name: this.name,
      status: this.currentStatus,
      currentTask: this.getCurrentTask(), // Needs to be implemented by concrete agents
      lastHeartbeat: new Date().toISOString(),
    };
  }

  /**
   * Retrieves the logs generated by this agent.
   * @returns An array of log entries.
   */
  public getLogs(): AgentLogEntry[] {
    return [...this.logs];
  }

  /**
   * Adds a log entry to the agent's internal log history.
   * @param message - The log message.
   * @param type - The type of log entry.
   * @param data - Optional additional data.
   */
  protected log(message: string, type: AgentLogEntry['type'] = 'info', data?: Record<string, any>): void {
    this.logs.push({
      timestamp: new Date().toISOString(),
      agentName: this.name,
      message,
      type,
      data,
    });
    console.log(`[${this.name}][${type.toUpperCase()}] ${message}`);
  }

  /**
   * Sets the agent's current status.
   * @param status - The new status.
   */
  protected setStatus(status: AgentStatus['status']): void {
    this.currentStatus = status;
    this.log(`Status changed to: ${status}`, 'info', { newStatus: status });
  }

  /**
   * Abstract method to get the current specific task the agent is working on.
   * Concrete agents must implement this to provide detailed status updates.
   */
  protected abstract getCurrentTask(): string;
}
